[package]
name = "open-sport-instrument"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bme280 = { path = "../bme280-rs" }
bme280 = "0.3.0"
esp-idf-sys = { version = "0.31", features = ["binstart"] }
esp-idf-svc = "0.40"
esp-idf-hal = "0.36"
embedded-svc = "0.20"
embedded-hal = "0.2"

[build-dependencies]
embuild = "0.28.2"
anyhow = "1"
